/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKaanGToken__factory } from './IKaanGToken__factory.js';
export { KaanYieldVault__factory } from './KaanYieldVault__factory.js';