/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface KaanYieldVaultInterface extends Interface {
    getFunction(nameOrSignature: "MONTHS" | "claimKaang" | "depositIndex" | "depositRent" | "estimatedAPY" | "kaanToken" | "kaangBackingPrice" | "kaangPerTokenStored" | "kaangToken" | "lastRentDeposit" | "monthlyDeposits" | "notifyTransfer" | "owner" | "pendingKaang" | "pendingKaangFor" | "redemptionContract" | "releaseUsdcToRedemption" | "renounceOwnership" | "setRedemptionContract" | "totalKaangMinted" | "totalRentDeposited" | "transferOwnership" | "usdcReserve" | "usdcToken" | "userKaangPerTokenPaid"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "KaangClaimed" | "OwnershipTransferred" | "RedemptionContractSet" | "RentDeposited" | "UsdcWithdrawnToRedemption"): EventFragment;

    encodeFunctionData(functionFragment: 'MONTHS', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimKaang', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositRent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'estimatedAPY', values?: undefined): string;
encodeFunctionData(functionFragment: 'kaanToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'kaangBackingPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'kaangPerTokenStored', values?: undefined): string;
encodeFunctionData(functionFragment: 'kaangToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastRentDeposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'monthlyDeposits', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'notifyTransfer', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingKaang', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'pendingKaangFor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'redemptionContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseUsdcToRedemption', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setRedemptionContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalKaangMinted', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalRentDeposited', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdcReserve', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'userKaangPerTokenPaid', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'MONTHS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimKaang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositRent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'estimatedAPY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kaanToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kaangBackingPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kaangPerTokenStored', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kaangToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastRentDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'monthlyDeposits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'notifyTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingKaang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingKaangFor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redemptionContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseUsdcToRedemption', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRedemptionContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalKaangMinted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRentDeposited', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcReserve', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userKaangPerTokenPaid', data: BytesLike): Result;
  }

  
    export namespace KaangClaimedEvent {
      export type InputTuple = [holder: AddressLike, kaangAmount: BigNumberish];
      export type OutputTuple = [holder: string, kaangAmount: bigint];
      export interface OutputObject {holder: string, kaangAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedemptionContractSetEvent {
      export type InputTuple = [redemption: AddressLike];
      export type OutputTuple = [redemption: string];
      export interface OutputObject {redemption: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RentDepositedEvent {
      export type InputTuple = [usdcAmount: BigNumberish, kaangEmitted: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [usdcAmount: bigint, kaangEmitted: bigint, timestamp: bigint];
      export interface OutputObject {usdcAmount: bigint, kaangEmitted: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UsdcWithdrawnToRedemptionEvent {
      export type InputTuple = [redemption: AddressLike, amount: BigNumberish];
      export type OutputTuple = [redemption: string, amount: bigint];
      export interface OutputObject {redemption: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KaanYieldVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): KaanYieldVault;
    waitForDeployment(): Promise<this>;

    interface: KaanYieldVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MONTHS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claimKaang: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    depositIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    depositRent: TypedContractMethod<
      [usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    estimatedAPY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    kaanToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    kaangBackingPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    kaangPerTokenStored: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    kaangToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lastRentDeposit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    monthlyDeposits: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    notifyTransfer: TypedContractMethod<
      [from: AddressLike, to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingKaang: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    pendingKaangFor: TypedContractMethod<
      [holder: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    redemptionContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    releaseUsdcToRedemption: TypedContractMethod<
      [to: AddressLike, usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setRedemptionContract: TypedContractMethod<
      [_redemption: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalKaangMinted: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalRentDeposited: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdcReserve: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    userKaangPerTokenPaid: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MONTHS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimKaang'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'depositRent'): TypedContractMethod<
      [usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'estimatedAPY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'kaanToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'kaangBackingPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'kaangPerTokenStored'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'kaangToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lastRentDeposit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'monthlyDeposits'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'notifyTransfer'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingKaang'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pendingKaangFor'): TypedContractMethod<
      [holder: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redemptionContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releaseUsdcToRedemption'): TypedContractMethod<
      [to: AddressLike, usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRedemptionContract'): TypedContractMethod<
      [_redemption: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalKaangMinted'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRentDeposited'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdcReserve'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'userKaangPerTokenPaid'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'KaangClaimed'): TypedContractEvent<KaangClaimedEvent.InputTuple, KaangClaimedEvent.OutputTuple, KaangClaimedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RedemptionContractSet'): TypedContractEvent<RedemptionContractSetEvent.InputTuple, RedemptionContractSetEvent.OutputTuple, RedemptionContractSetEvent.OutputObject>;
getEvent(key: 'RentDeposited'): TypedContractEvent<RentDepositedEvent.InputTuple, RentDepositedEvent.OutputTuple, RentDepositedEvent.OutputObject>;
getEvent(key: 'UsdcWithdrawnToRedemption'): TypedContractEvent<UsdcWithdrawnToRedemptionEvent.InputTuple, UsdcWithdrawnToRedemptionEvent.OutputTuple, UsdcWithdrawnToRedemptionEvent.OutputObject>;

    filters: {
      
      'KaangClaimed(address,uint256)': TypedContractEvent<KaangClaimedEvent.InputTuple, KaangClaimedEvent.OutputTuple, KaangClaimedEvent.OutputObject>;
      KaangClaimed: TypedContractEvent<KaangClaimedEvent.InputTuple, KaangClaimedEvent.OutputTuple, KaangClaimedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RedemptionContractSet(address)': TypedContractEvent<RedemptionContractSetEvent.InputTuple, RedemptionContractSetEvent.OutputTuple, RedemptionContractSetEvent.OutputObject>;
      RedemptionContractSet: TypedContractEvent<RedemptionContractSetEvent.InputTuple, RedemptionContractSetEvent.OutputTuple, RedemptionContractSetEvent.OutputObject>;
    

      'RentDeposited(uint256,uint256,uint256)': TypedContractEvent<RentDepositedEvent.InputTuple, RentDepositedEvent.OutputTuple, RentDepositedEvent.OutputObject>;
      RentDeposited: TypedContractEvent<RentDepositedEvent.InputTuple, RentDepositedEvent.OutputTuple, RentDepositedEvent.OutputObject>;
    

      'UsdcWithdrawnToRedemption(address,uint256)': TypedContractEvent<UsdcWithdrawnToRedemptionEvent.InputTuple, UsdcWithdrawnToRedemptionEvent.OutputTuple, UsdcWithdrawnToRedemptionEvent.OutputObject>;
      UsdcWithdrawnToRedemption: TypedContractEvent<UsdcWithdrawnToRedemptionEvent.InputTuple, UsdcWithdrawnToRedemptionEvent.OutputTuple, UsdcWithdrawnToRedemptionEvent.OutputObject>;
    
    };
  }