/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'KaanSale', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KaanSale__factory>
getContractFactory(name: 'IKaanYieldVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IKaanYieldVault__factory>
getContractFactory(name: 'KaanToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KaanToken__factory>
getContractFactory(name: 'KaanYieldVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KaanYieldVault__factory>
getContractFactory(name: 'MockUSDC', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDC__factory>

  getContractAt(name: 'KaanSale', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KaanSale>
getContractAt(name: 'IKaanYieldVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IKaanYieldVault>
getContractAt(name: 'KaanToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KaanToken>
getContractAt(name: 'KaanYieldVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KaanYieldVault>
getContractAt(name: 'MockUSDC', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDC>

  deployContract(name: 'KaanSale', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KaanSale>
deployContract(name: 'IKaanYieldVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKaanYieldVault>
deployContract(name: 'KaanToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KaanToken>
deployContract(name: 'KaanYieldVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KaanYieldVault>
deployContract(name: 'MockUSDC', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>

  deployContract(name: 'KaanSale', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KaanSale>
deployContract(name: 'IKaanYieldVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IKaanYieldVault>
deployContract(name: 'KaanToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KaanToken>
deployContract(name: 'KaanYieldVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KaanYieldVault>
deployContract(name: 'MockUSDC', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDC>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  