/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface KaanYieldVaultInterface extends Interface {
    getFunction(nameOrSignature: "MONTHS" | "claimYield" | "depositIndex" | "depositRent" | "estimatedAPY" | "kaanToken" | "lastRentDeposit" | "monthlyDeposits" | "notifyTransfer" | "owner" | "pendingYield" | "renounceOwnership" | "rewardPerTokenStored" | "rewards" | "totalRentDeposited" | "transferOwnership" | "usdcToken" | "userRewardPerTokenPaid"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "RentDeposited" | "YieldClaimed"): EventFragment;

    encodeFunctionData(functionFragment: 'MONTHS', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimYield', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'depositRent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'estimatedAPY', values?: undefined): string;
encodeFunctionData(functionFragment: 'kaanToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'lastRentDeposit', values?: undefined): string;
encodeFunctionData(functionFragment: 'monthlyDeposits', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'notifyTransfer', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingYield', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardPerTokenStored', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalRentDeposited', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'userRewardPerTokenPaid', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'MONTHS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimYield', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'depositRent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'estimatedAPY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kaanToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastRentDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'monthlyDeposits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'notifyTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingYield', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardPerTokenStored', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalRentDeposited', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'userRewardPerTokenPaid', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RentDepositedEvent {
      export type InputTuple = [amount: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [amount: bigint, timestamp: bigint];
      export interface OutputObject {amount: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace YieldClaimedEvent {
      export type InputTuple = [holder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [holder: string, amount: bigint];
      export interface OutputObject {holder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KaanYieldVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): KaanYieldVault;
    waitForDeployment(): Promise<this>;

    interface: KaanYieldVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MONTHS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claimYield: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    depositIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    depositRent: TypedContractMethod<
      [usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    estimatedAPY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    kaanToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lastRentDeposit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    monthlyDeposits: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    notifyTransfer: TypedContractMethod<
      [from: AddressLike, to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingYield: TypedContractMethod<
      [holder: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rewardPerTokenStored: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rewards: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    totalRentDeposited: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    userRewardPerTokenPaid: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MONTHS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimYield'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'depositIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'depositRent'): TypedContractMethod<
      [usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'estimatedAPY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'kaanToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lastRentDeposit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'monthlyDeposits'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'notifyTransfer'): TypedContractMethod<
      [from: AddressLike, to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingYield'): TypedContractMethod<
      [holder: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rewardPerTokenStored'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rewards'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalRentDeposited'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'userRewardPerTokenPaid'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RentDeposited'): TypedContractEvent<RentDepositedEvent.InputTuple, RentDepositedEvent.OutputTuple, RentDepositedEvent.OutputObject>;
getEvent(key: 'YieldClaimed'): TypedContractEvent<YieldClaimedEvent.InputTuple, YieldClaimedEvent.OutputTuple, YieldClaimedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RentDeposited(uint256,uint256)': TypedContractEvent<RentDepositedEvent.InputTuple, RentDepositedEvent.OutputTuple, RentDepositedEvent.OutputObject>;
      RentDeposited: TypedContractEvent<RentDepositedEvent.InputTuple, RentDepositedEvent.OutputTuple, RentDepositedEvent.OutputObject>;
    

      'YieldClaimed(address,uint256)': TypedContractEvent<YieldClaimedEvent.InputTuple, YieldClaimedEvent.OutputTuple, YieldClaimedEvent.OutputObject>;
      YieldClaimed: TypedContractEvent<YieldClaimedEvent.InputTuple, YieldClaimedEvent.OutputTuple, YieldClaimedEvent.OutputObject>;
    
    };
  }