/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface KaanSaleInterface extends Interface {
    getFunction(nameOrSignature: "MAX_FOR_SALE" | "PRICE" | "addToWhitelist" | "buyKaan" | "kaanToken" | "owner" | "removeFromWhitelist" | "renounceOwnership" | "saleActive" | "setSaleActive" | "setWhitelistEnabled" | "totalSold" | "transferOwnership" | "usdcToken" | "whitelistEnabled" | "whitelisted" | "withdrawUSDC"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "TokensPurchased"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_FOR_SALE', values?: undefined): string;
encodeFunctionData(functionFragment: 'PRICE', values?: undefined): string;
encodeFunctionData(functionFragment: 'addToWhitelist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'buyKaan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'kaanToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeFromWhitelist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'saleActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'setSaleActive', values: [boolean]): string;
encodeFunctionData(functionFragment: 'setWhitelistEnabled', values: [boolean]): string;
encodeFunctionData(functionFragment: 'totalSold', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdcToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'whitelistEnabled', values?: undefined): string;
encodeFunctionData(functionFragment: 'whitelisted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawUSDC', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_FOR_SALE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'PRICE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addToWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buyKaan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kaanToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeFromWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'saleActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setSaleActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWhitelistEnabled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdcToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelistEnabled', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'whitelisted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawUSDC', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokensPurchasedEvent {
      export type InputTuple = [buyer: AddressLike, kaanAmount: BigNumberish, usdcPaid: BigNumberish];
      export type OutputTuple = [buyer: string, kaanAmount: bigint, usdcPaid: bigint];
      export interface OutputObject {buyer: string, kaanAmount: bigint, usdcPaid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KaanSale extends BaseContract {
    
    connect(runner?: ContractRunner | null): KaanSale;
    waitForDeployment(): Promise<this>;

    interface: KaanSaleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_FOR_SALE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    PRICE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addToWhitelist: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    buyKaan: TypedContractMethod<
      [kaanAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    kaanToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    removeFromWhitelist: TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    saleActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    setSaleActive: TypedContractMethod<
      [_active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setWhitelistEnabled: TypedContractMethod<
      [_enabled: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    totalSold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdcToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    whitelistEnabled: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    whitelisted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    withdrawUSDC: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_FOR_SALE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'PRICE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addToWhitelist'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buyKaan'): TypedContractMethod<
      [kaanAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'kaanToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'removeFromWhitelist'): TypedContractMethod<
      [account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'saleActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setSaleActive'): TypedContractMethod<
      [_active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWhitelistEnabled'): TypedContractMethod<
      [_enabled: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalSold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdcToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'whitelistEnabled'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'whitelisted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawUSDC'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TokensPurchased'): TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TokensPurchased(address,uint256,uint256)': TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
      TokensPurchased: TypedContractEvent<TokensPurchasedEvent.InputTuple, TokensPurchasedEvent.OutputTuple, TokensPurchasedEvent.OutputObject>;
    
    };
  }