/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKaanGYieldVault, IKaanGYieldVaultInterface } from "../../KaanGToken.sol/IKaanGYieldVault.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      }
    ],
    "name": "notifyTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKaanGYieldVault__factory {
    static readonly abi = _abi;
    static createInterface(): IKaanGYieldVaultInterface {
      return new Interface(_abi) as IKaanGYieldVaultInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKaanGYieldVault {
      return new Contract(address, _abi, runner) as unknown as IKaanGYieldVault;
    }
  }
  