/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IKaanGYieldVault__factory } from './IKaanGYieldVault__factory.js';
export { KaanGToken__factory } from './KaanGToken__factory.js';