/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKaanYieldVault, IKaanYieldVaultInterface } from "../../KaanRedemption.sol/IKaanYieldVault.js";

  const _abi = [
  {
    "inputs": [],
    "name": "kaangBackingPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "redemptionContract",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "usdcAmount",
        "type": "uint256"
      }
    ],
    "name": "releaseUsdcToRedemption",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKaanYieldVault__factory {
    static readonly abi = _abi;
    static createInterface(): IKaanYieldVaultInterface {
      return new Interface(_abi) as IKaanYieldVaultInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKaanYieldVault {
      return new Contract(address, _abi, runner) as unknown as IKaanYieldVault;
    }
  }
  