/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKaanBuildVault, IKaanBuildVaultInterface } from "../../KaanRedemption.sol/IKaanBuildVault.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "investor",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "projectId",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "usdcAmount",
        "type": "uint256"
      }
    ],
    "name": "investFrom",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKaanBuildVault__factory {
    static readonly abi = _abi;
    static createInterface(): IKaanBuildVaultInterface {
      return new Interface(_abi) as IKaanBuildVaultInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKaanBuildVault {
      return new Contract(address, _abi, runner) as unknown as IKaanBuildVault;
    }
  }
  