/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKaanYieldVault, IKaanYieldVaultInterface } from "../../KaanToken.sol/IKaanYieldVault.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "from",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      }
    ],
    "name": "notifyTransfer",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKaanYieldVault__factory {
    static readonly abi = _abi;
    static createInterface(): IKaanYieldVaultInterface {
      return new Interface(_abi) as IKaanYieldVaultInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKaanYieldVault {
      return new Contract(address, _abi, runner) as unknown as IKaanYieldVault;
    }
  }
  