/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace KaanBuildVault {
      
    export type InvestmentStruct = {usdcDeposited: BigNumberish, claimed: boolean}

    export type InvestmentStructOutput = [usdcDeposited: bigint, claimed: boolean] & {usdcDeposited: bigint, claimed: boolean }
  

    export type ProjectStruct = {name: string, targetUsdc: BigNumberish, raisedUsdc: BigNumberish, releasedUsdc: BigNumberish, kaangPerUsdc: BigNumberish, milestoneCount: BigNumberish, milestonesComplete: BigNumberish, status: BigNumberish, builder: AddressLike}

    export type ProjectStructOutput = [name: string, targetUsdc: bigint, raisedUsdc: bigint, releasedUsdc: bigint, kaangPerUsdc: bigint, milestoneCount: bigint, milestonesComplete: bigint, status: bigint, builder: string] & {name: string, targetUsdc: bigint, raisedUsdc: bigint, releasedUsdc: bigint, kaangPerUsdc: bigint, milestoneCount: bigint, milestonesComplete: bigint, status: bigint, builder: string }
  
    }

  export interface KaanBuildVaultInterface extends Interface {
    getFunction(nameOrSignature: "autoCompound" | "autoCompoundProjectId" | "cancelProject" | "claimKaang" | "completeMilestone" | "createProject" | "fundingProgress" | "getInvestment" | "getProject" | "invest" | "investFrom" | "investments" | "kaang" | "owner" | "projectCount" | "projects" | "receiveAutoCompound" | "redemptionContract" | "redemptionSet" | "refund" | "renounceOwnership" | "setAutoCompoundProject" | "setRedemptionContract" | "startBuilding" | "toggleAutoCompound" | "transferOwnership" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AutoCompoundDeposit" | "AutoCompoundToggled" | "Invested" | "KaangClaimed" | "MilestoneCompleted" | "OwnershipTransferred" | "ProjectCompleted" | "ProjectCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'autoCompound', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'autoCompoundProjectId', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancelProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimKaang', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'completeMilestone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createProject', values: [string, BigNumberish, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'fundingProgress', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getInvestment', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'invest', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'investFrom', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'investments', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'kaang', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'projectCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'projects', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'receiveAutoCompound', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'redemptionContract', values?: undefined): string;
encodeFunctionData(functionFragment: 'redemptionSet', values?: undefined): string;
encodeFunctionData(functionFragment: 'refund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAutoCompoundProject', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setRedemptionContract', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'startBuilding', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'toggleAutoCompound', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'autoCompound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'autoCompoundProjectId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimKaang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completeMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundingProgress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInvestment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'invest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'investFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'investments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kaang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projectCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'projects', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'receiveAutoCompound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redemptionContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redemptionSet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAutoCompoundProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRedemptionContract', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startBuilding', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'toggleAutoCompound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace AutoCompoundDepositEvent {
      export type InputTuple = [investor: AddressLike, amount: BigNumberish, projectId: BigNumberish];
      export type OutputTuple = [investor: string, amount: bigint, projectId: bigint];
      export interface OutputObject {investor: string, amount: bigint, projectId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AutoCompoundToggledEvent {
      export type InputTuple = [investor: AddressLike, enabled: boolean];
      export type OutputTuple = [investor: string, enabled: boolean];
      export interface OutputObject {investor: string, enabled: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvestedEvent {
      export type InputTuple = [projectId: BigNumberish, investor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [projectId: bigint, investor: string, amount: bigint];
      export interface OutputObject {projectId: bigint, investor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace KaangClaimedEvent {
      export type InputTuple = [projectId: BigNumberish, investor: AddressLike, kaangAmount: BigNumberish];
      export type OutputTuple = [projectId: bigint, investor: string, kaangAmount: bigint];
      export interface OutputObject {projectId: bigint, investor: string, kaangAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneCompletedEvent {
      export type InputTuple = [projectId: BigNumberish, milestone: BigNumberish, released: BigNumberish];
      export type OutputTuple = [projectId: bigint, milestone: bigint, released: bigint];
      export interface OutputObject {projectId: bigint, milestone: bigint, released: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCompletedEvent {
      export type InputTuple = [projectId: BigNumberish];
      export type OutputTuple = [projectId: bigint];
      export interface OutputObject {projectId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProjectCreatedEvent {
      export type InputTuple = [id: BigNumberish, name: string, targetUsdc: BigNumberish];
      export type OutputTuple = [id: bigint, name: string, targetUsdc: bigint];
      export interface OutputObject {id: bigint, name: string, targetUsdc: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KaanBuildVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): KaanBuildVault;
    waitForDeployment(): Promise<this>;

    interface: KaanBuildVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    autoCompound: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    autoCompoundProjectId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    cancelProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimKaang: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    completeMilestone: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createProject: TypedContractMethod<
      [name: string, targetUsdc: BigNumberish, kaangPerUsdcScaled: BigNumberish, milestoneCount: BigNumberish, builder: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    fundingProgress: TypedContractMethod<
      [projectId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getInvestment: TypedContractMethod<
      [projectId: BigNumberish, investor: AddressLike, ],
      [KaanBuildVault.InvestmentStructOutput],
      'view'
    >
    

    
    getProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [KaanBuildVault.ProjectStructOutput],
      'view'
    >
    

    
    invest: TypedContractMethod<
      [projectId: BigNumberish, usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    investFrom: TypedContractMethod<
      [investor: AddressLike, projectId: BigNumberish, usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    investments: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[bigint, boolean] & {usdcDeposited: bigint, claimed: boolean }],
      'view'
    >
    

    
    kaang: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    projectCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    projects: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, string] & {name: string, targetUsdc: bigint, raisedUsdc: bigint, releasedUsdc: bigint, kaangPerUsdc: bigint, milestoneCount: bigint, milestonesComplete: bigint, status: bigint, builder: string }],
      'view'
    >
    

    
    receiveAutoCompound: TypedContractMethod<
      [investor: AddressLike, usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    redemptionContract: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    redemptionSet: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setAutoCompoundProject: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setRedemptionContract: TypedContractMethod<
      [_redemption: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    startBuilding: TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    toggleAutoCompound: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'autoCompound'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'autoCompoundProjectId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimKaang'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'completeMilestone'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createProject'): TypedContractMethod<
      [name: string, targetUsdc: BigNumberish, kaangPerUsdcScaled: BigNumberish, milestoneCount: BigNumberish, builder: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundingProgress'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getInvestment'): TypedContractMethod<
      [projectId: BigNumberish, investor: AddressLike, ],
      [KaanBuildVault.InvestmentStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [KaanBuildVault.ProjectStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'invest'): TypedContractMethod<
      [projectId: BigNumberish, usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'investFrom'): TypedContractMethod<
      [investor: AddressLike, projectId: BigNumberish, usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'investments'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [[bigint, boolean] & {usdcDeposited: bigint, claimed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'kaang'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'projectCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'projects'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, string] & {name: string, targetUsdc: bigint, raisedUsdc: bigint, releasedUsdc: bigint, kaangPerUsdc: bigint, milestoneCount: bigint, milestonesComplete: bigint, status: bigint, builder: string }],
      'view'
    >;
getFunction(nameOrSignature: 'receiveAutoCompound'): TypedContractMethod<
      [investor: AddressLike, usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'redemptionContract'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'redemptionSet'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAutoCompoundProject'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRedemptionContract'): TypedContractMethod<
      [_redemption: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startBuilding'): TypedContractMethod<
      [projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'toggleAutoCompound'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AutoCompoundDeposit'): TypedContractEvent<AutoCompoundDepositEvent.InputTuple, AutoCompoundDepositEvent.OutputTuple, AutoCompoundDepositEvent.OutputObject>;
getEvent(key: 'AutoCompoundToggled'): TypedContractEvent<AutoCompoundToggledEvent.InputTuple, AutoCompoundToggledEvent.OutputTuple, AutoCompoundToggledEvent.OutputObject>;
getEvent(key: 'Invested'): TypedContractEvent<InvestedEvent.InputTuple, InvestedEvent.OutputTuple, InvestedEvent.OutputObject>;
getEvent(key: 'KaangClaimed'): TypedContractEvent<KaangClaimedEvent.InputTuple, KaangClaimedEvent.OutputTuple, KaangClaimedEvent.OutputObject>;
getEvent(key: 'MilestoneCompleted'): TypedContractEvent<MilestoneCompletedEvent.InputTuple, MilestoneCompletedEvent.OutputTuple, MilestoneCompletedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProjectCompleted'): TypedContractEvent<ProjectCompletedEvent.InputTuple, ProjectCompletedEvent.OutputTuple, ProjectCompletedEvent.OutputObject>;
getEvent(key: 'ProjectCreated'): TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;

    filters: {
      
      'AutoCompoundDeposit(address,uint256,uint256)': TypedContractEvent<AutoCompoundDepositEvent.InputTuple, AutoCompoundDepositEvent.OutputTuple, AutoCompoundDepositEvent.OutputObject>;
      AutoCompoundDeposit: TypedContractEvent<AutoCompoundDepositEvent.InputTuple, AutoCompoundDepositEvent.OutputTuple, AutoCompoundDepositEvent.OutputObject>;
    

      'AutoCompoundToggled(address,bool)': TypedContractEvent<AutoCompoundToggledEvent.InputTuple, AutoCompoundToggledEvent.OutputTuple, AutoCompoundToggledEvent.OutputObject>;
      AutoCompoundToggled: TypedContractEvent<AutoCompoundToggledEvent.InputTuple, AutoCompoundToggledEvent.OutputTuple, AutoCompoundToggledEvent.OutputObject>;
    

      'Invested(uint256,address,uint256)': TypedContractEvent<InvestedEvent.InputTuple, InvestedEvent.OutputTuple, InvestedEvent.OutputObject>;
      Invested: TypedContractEvent<InvestedEvent.InputTuple, InvestedEvent.OutputTuple, InvestedEvent.OutputObject>;
    

      'KaangClaimed(uint256,address,uint256)': TypedContractEvent<KaangClaimedEvent.InputTuple, KaangClaimedEvent.OutputTuple, KaangClaimedEvent.OutputObject>;
      KaangClaimed: TypedContractEvent<KaangClaimedEvent.InputTuple, KaangClaimedEvent.OutputTuple, KaangClaimedEvent.OutputObject>;
    

      'MilestoneCompleted(uint256,uint256,uint256)': TypedContractEvent<MilestoneCompletedEvent.InputTuple, MilestoneCompletedEvent.OutputTuple, MilestoneCompletedEvent.OutputObject>;
      MilestoneCompleted: TypedContractEvent<MilestoneCompletedEvent.InputTuple, MilestoneCompletedEvent.OutputTuple, MilestoneCompletedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProjectCompleted(uint256)': TypedContractEvent<ProjectCompletedEvent.InputTuple, ProjectCompletedEvent.OutputTuple, ProjectCompletedEvent.OutputObject>;
      ProjectCompleted: TypedContractEvent<ProjectCompletedEvent.InputTuple, ProjectCompletedEvent.OutputTuple, ProjectCompletedEvent.OutputObject>;
    

      'ProjectCreated(uint256,string,uint256)': TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
      ProjectCreated: TypedContractEvent<ProjectCreatedEvent.InputTuple, ProjectCreatedEvent.OutputTuple, ProjectCreatedEvent.OutputObject>;
    
    };
  }