/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IKaanYieldVaultInterface extends Interface {
    getFunction(nameOrSignature: "kaangBackingPrice" | "releaseUsdcToRedemption"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'kaangBackingPrice', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseUsdcToRedemption', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'kaangBackingPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseUsdcToRedemption', data: BytesLike): Result;
  }

  

  export interface IKaanYieldVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): IKaanYieldVault;
    waitForDeployment(): Promise<this>;

    interface: IKaanYieldVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    kaangBackingPrice: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    releaseUsdcToRedemption: TypedContractMethod<
      [redemptionContract: AddressLike, usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'kaangBackingPrice'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'releaseUsdcToRedemption'): TypedContractMethod<
      [redemptionContract: AddressLike, usdcAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }