/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface KaanRedemptionInterface extends Interface {
    getFunction(nameOrSignature: "buildVault" | "buildVaultSet" | "cashRedemptionOpen" | "kaang" | "owner" | "previewCashOut" | "redeemForCash" | "reinvestInProject" | "renounceOwnership" | "setBuildVault" | "setCashRedemptionOpen" | "totalKaangRedeemedForCash" | "totalKaangReinvested" | "totalUsdcPaidOut" | "transferOwnership" | "usdc" | "yieldVault"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BuildVaultSet" | "CashRedemptionToggled" | "OwnershipTransferred" | "RedeemedForCash" | "Reinvested"): EventFragment;

    encodeFunctionData(functionFragment: 'buildVault', values?: undefined): string;
encodeFunctionData(functionFragment: 'buildVaultSet', values?: undefined): string;
encodeFunctionData(functionFragment: 'cashRedemptionOpen', values?: undefined): string;
encodeFunctionData(functionFragment: 'kaang', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'previewCashOut', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'redeemForCash', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'reinvestInProject', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setBuildVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setCashRedemptionOpen', values: [boolean]): string;
encodeFunctionData(functionFragment: 'totalKaangRedeemedForCash', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalKaangReinvested', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalUsdcPaidOut', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'yieldVault', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buildVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buildVaultSet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cashRedemptionOpen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'kaang', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'previewCashOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'redeemForCash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reinvestInProject', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setBuildVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCashRedemptionOpen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalKaangRedeemedForCash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalKaangReinvested', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalUsdcPaidOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'yieldVault', data: BytesLike): Result;
  }

  
    export namespace BuildVaultSetEvent {
      export type InputTuple = [vault: AddressLike];
      export type OutputTuple = [vault: string];
      export interface OutputObject {vault: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CashRedemptionToggledEvent {
      export type InputTuple = [open: boolean];
      export type OutputTuple = [open: boolean];
      export interface OutputObject {open: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RedeemedForCashEvent {
      export type InputTuple = [holder: AddressLike, kaangBurned: BigNumberish, usdcReceived: BigNumberish];
      export type OutputTuple = [holder: string, kaangBurned: bigint, usdcReceived: bigint];
      export interface OutputObject {holder: string, kaangBurned: bigint, usdcReceived: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ReinvestedEvent {
      export type InputTuple = [holder: AddressLike, kaangBurned: BigNumberish, usdcRouted: BigNumberish, projectId: BigNumberish];
      export type OutputTuple = [holder: string, kaangBurned: bigint, usdcRouted: bigint, projectId: bigint];
      export interface OutputObject {holder: string, kaangBurned: bigint, usdcRouted: bigint, projectId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface KaanRedemption extends BaseContract {
    
    connect(runner?: ContractRunner | null): KaanRedemption;
    waitForDeployment(): Promise<this>;

    interface: KaanRedemptionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buildVault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    buildVaultSet: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    cashRedemptionOpen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    kaang: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    previewCashOut: TypedContractMethod<
      [kaangAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    redeemForCash: TypedContractMethod<
      [kaangAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    reinvestInProject: TypedContractMethod<
      [kaangAmount: BigNumberish, projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setBuildVault: TypedContractMethod<
      [_vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setCashRedemptionOpen: TypedContractMethod<
      [_open: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    totalKaangRedeemedForCash: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalKaangReinvested: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalUsdcPaidOut: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    yieldVault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buildVault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'buildVaultSet'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'cashRedemptionOpen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'kaang'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'previewCashOut'): TypedContractMethod<
      [kaangAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'redeemForCash'): TypedContractMethod<
      [kaangAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reinvestInProject'): TypedContractMethod<
      [kaangAmount: BigNumberish, projectId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setBuildVault'): TypedContractMethod<
      [_vault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setCashRedemptionOpen'): TypedContractMethod<
      [_open: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalKaangRedeemedForCash'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalKaangReinvested'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalUsdcPaidOut'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'yieldVault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'BuildVaultSet'): TypedContractEvent<BuildVaultSetEvent.InputTuple, BuildVaultSetEvent.OutputTuple, BuildVaultSetEvent.OutputObject>;
getEvent(key: 'CashRedemptionToggled'): TypedContractEvent<CashRedemptionToggledEvent.InputTuple, CashRedemptionToggledEvent.OutputTuple, CashRedemptionToggledEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RedeemedForCash'): TypedContractEvent<RedeemedForCashEvent.InputTuple, RedeemedForCashEvent.OutputTuple, RedeemedForCashEvent.OutputObject>;
getEvent(key: 'Reinvested'): TypedContractEvent<ReinvestedEvent.InputTuple, ReinvestedEvent.OutputTuple, ReinvestedEvent.OutputObject>;

    filters: {
      
      'BuildVaultSet(address)': TypedContractEvent<BuildVaultSetEvent.InputTuple, BuildVaultSetEvent.OutputTuple, BuildVaultSetEvent.OutputObject>;
      BuildVaultSet: TypedContractEvent<BuildVaultSetEvent.InputTuple, BuildVaultSetEvent.OutputTuple, BuildVaultSetEvent.OutputObject>;
    

      'CashRedemptionToggled(bool)': TypedContractEvent<CashRedemptionToggledEvent.InputTuple, CashRedemptionToggledEvent.OutputTuple, CashRedemptionToggledEvent.OutputObject>;
      CashRedemptionToggled: TypedContractEvent<CashRedemptionToggledEvent.InputTuple, CashRedemptionToggledEvent.OutputTuple, CashRedemptionToggledEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RedeemedForCash(address,uint256,uint256)': TypedContractEvent<RedeemedForCashEvent.InputTuple, RedeemedForCashEvent.OutputTuple, RedeemedForCashEvent.OutputObject>;
      RedeemedForCash: TypedContractEvent<RedeemedForCashEvent.InputTuple, RedeemedForCashEvent.OutputTuple, RedeemedForCashEvent.OutputObject>;
    

      'Reinvested(address,uint256,uint256,uint256)': TypedContractEvent<ReinvestedEvent.InputTuple, ReinvestedEvent.OutputTuple, ReinvestedEvent.OutputObject>;
      Reinvested: TypedContractEvent<ReinvestedEvent.InputTuple, ReinvestedEvent.OutputTuple, ReinvestedEvent.OutputObject>;
    
    };
  }