/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IKaanGToken, IKaanGTokenInterface } from "../../KaanBuildVault.sol/IKaanGToken.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "mintFromBuild",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IKaanGToken__factory {
    static readonly abi = _abi;
    static createInterface(): IKaanGTokenInterface {
      return new Interface(_abi) as IKaanGTokenInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IKaanGToken {
      return new Contract(address, _abi, runner) as unknown as IKaanGToken;
    }
  }
  