/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IKaanGYieldVault } from './IKaanGYieldVault.js';
export type { KaanGToken } from './KaanGToken.js';